vendor: QBO LLC
name: qbo cloud
version: cloud-stage-4.3.0-25d2858bb
website_url: https://www.qbo.io
repo_url: https://github.com/alexeadem/qbo-home
documentation_url: https://docs.qbo.io
product_logo_url: https://raw.githubusercontent.com/alexeadem/qbo-home/master/qbo_250x150.svg
type: distribution
description: "Qbo is a pure containerized Kubernetes distribution delivering metal performance with zero virtualization. It brings a faster and simplified cloud experience for anyone, anywhere."
contact_email_address: info@qbo.io
