vendor: Kubermatic
name: Kubermatic Kubernetes Platform
description: 'Kubermatic Kubernetes Platform is in an open source project to centrally manage the global automation of thousands of Kubernetes clusters across multicloud, on-prem and edge.'
version: v2.20
website_url: https://kubermatic.com
documentation_url: https://docs.kubermatic.com/kubermatic/
repo_url: https://github.com/kubermatic/kubermatic
type: Distribution
product_logo_url: https://drive.google.com/file/d/1Y73nNAI4qkLA3bbf6mmLN7hagjd2Z3s_/view?usp=sharing
